- name: Install Dependencies
        run: |
          npm init -y
          # هذا السطر مهم جداً
          npm pkg set type="module" 
          npm install playwright playwright-stealth
          npx playwright install chromium --with-deps
          sudo apt-get install -y ffmpeg
